---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - nvim
        - brave-browser
        - firefox
        - flatpak
        - steam
        - kitty
        - github-desktop
        - discord
        - gparted
        - vlc
        - nfs-common
        - libreoffice
        - chezmoi

  - name: copy wallpaper file
    copy:
      src: files/wyoming.jpg
      dest: /usr/share/backgrounds/wyoming.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: reilandeubank
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/wyoming.jpg'"

  - name: set wallpaper position
    become_user: reilandeubank
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  # - name: Create mount point directory
  #   file:
  #     path: /mnt/media-share
  #     state: directory
  #
  # - name: Add nfs entry to fstab
  #   lineinfile:
  #     path: /etc/fstab
  #     line: "192.168.0.101:/mnt/media/media-share /mnt/media-share nfs default 0 0"
  #     insertafter: EOF

  # - name: Initialize dotfiles repo
  #   become_user: reilandeubank
  #   command: chezmoi init https://github.com/reilandeubank/dotfiles.git

  - name: Apply dotfiles configuration
    become_user: reilandeubank
    command: chezmoi apply
